# Generated by Django 4.2.11 on 2024-03-13 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_templates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canvastemplate',
            old_name='konvaObject',
            new_name='konva_objects',
        ),
    ]
